root: true
env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  'import/order':
    - warn
    - newlines-between: always
  'import/no-deprecated': error
  'import/prefer-default-export': off
  '@typescript-eslint/explicit-function-return-type': off
  'no-unused-vars': off
  '@typescript-eslint/no-unused-vars': ["off"]
